### ISSUE TITLE
Create demo HTTP App

### ISSUE THREAD

**Issue by elventear** [radiasoft/comsoljupyter#1]
The demo HTTP server will serve as launch point for a Comsol session. 

Requirements:
- [x] Have internal user tracking.
- [x] Render a page with a link that will launch Comsol with a running session.
- [x] Make a Comsol session sticky so that the same user will open the same Comsol session.

**Comment by elventear** [comment]
Proposed design:

When a user clicks on the link to launch Comsol, a new Window will open with a web request that will execute the following:

1. Get a new Comsol session.
2. Create a new cookie `RSCOMSOL`. 
3. Do a REST request to configure the Comsol proxy with the information necessary to modify requests to allow for access to Comsol.
4. Do a redirect to the Comsol Proxy.

**Comment by robnagler** [comment]
Maybe need to say that "session" is the same as "user". We'll need to know which user is running so we can save/restore the user's state when the session is restarted (user context switch).

Do we also want to talk about save/restore of the user's state in COMSOL? I think COMSOL just stores state in a file structure, but I could be wrong. It would be cool if we could just swap out directories when a context switch occurs.

**Comment by elventear** [comment]
Master branch fulfills the requirements as of f85c383a2a1c9e37bef9ee80d6b36c2ce9c67457.
